# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false
before_install:
  - sudo apt-get install -y libprotobuf-dev
  - sudo apt-get install -y protobuf-compiler
addons:
  apt:
    update: true